site_name: Triagil

repo_name: 'GitHub Repository'
repo_url: 'https://github.com/UnBArqDsw/2020.1_G1_Triagil'

copyright: 'Copyright &copy; 2020 UnB Gama - FGA'

theme:
  name: material
  language: 'pt'
  logo: 'images/icon-white.png'
  favicon: 'images/icon-color-favicon.ico'
  palette:
    primary: 'light blue'
    accent: 'red'
  font:
    text: 'Roboto'

nav:
  - Início: index.md
  - Base:
    # - Design Sprint: base/design_sprint/ds.md
    - Requisitos:
      - Pré-Rastriabilidade:
        - 5W2H: base/requisitos/pre-rastriabilidade/5w2h.md
        - Rich Picture: base/requisitos/pre-rastriabilidade/rp.md
        # - Causa-Efeito: base/requisitos/pre-rastriabilidade/causa_e_efeito.md
      - Elicitação:
        - Brainstorming: base/requisitos/elicitacao/brainstorming.md
        - Entrevista: base/requisitos/elicitacao/entrevista.md
        - Questionário: base/requisitos/elicitacao/questionario.md
        # - Storyboard: base/requisitos/elicitacao/storyboard.md
      - Modelagem:
        - Backlog do Produto: base/requisitos/modelagem/backlog.md
      # - Análise:
      #   - Verificação: base/requisitos/analise/verificacao.md
      #   - Validação: base/requisitos/analise/validacao.md
    - Plano de Custos: base/documentos/plano_custos.md
    - Plano de Riscos: base/documentos/plano_risco.md    
    - Apresentação:
      - Metodologias:
        - Scrum: base/apresentacao/metodologia/scrum.md
        - Programação Extrema(XP): base/apresentacao/metodologia/xp.md
    - Modelagem BPMN: base/modelagem_bpmn/bpmn.md
    # - Iniciativas Extras:
