site_name: Triagil

repo_name: '2020.1_G1_Triagil'

copyright: 'Copyright &copy; 2020 Universidade de Brasilia - Campus Gama'

theme:
  name: material
  language: 'pt'
  logo: 'images/icon-white.png'
  favicon: 'images/favicon.ico'
  palette:
    primary: 'light blue'
    accent: 'red'
  font:
    text: 'Montserrat'
    code: 'sans-serif'

nav:
  - Início: index.md
  - Base:
    - Abordagens Específicas:
      - Pré-Rastriabilidade:
        - Rich Picture: abordagensEspecificas/pre/rp.md
      - Elicitação:
        - Brainstorming: abordagensEspecificas/elicitacao/brainstorming.md
        - Entrevista: abordagensEspecificas/elicitacao/entrevista.md
        - Questionário: abordagensEspecificas/elicitacao/questionario.md
        - Storyboard: abordagensEspecificas/elicitacao/storyboard.md
      - Modelagem:
        - Backlog do Produto: abordagensEspecificas/modelagem/backlog.md
      - Análise:
        - Verificação: abordagensEspecificas/analise/verificacao.md
        - Validação: abordagensEspecificas/analise/validacao.md
    - Apresentação:
      - Metodologias:
        - Scrum: apresentacao/metodologia/scrum.md
        - Programação Extrema(XP): apresentacao/metodologia/xp.md
    - Modelagem BPMN: modelagemBPMN/bpmn.md
    - Iniciativas Extras: extras/extras.md
