site_name: Triagil

repo_name: 'GitHub Repository'
repo_url: 'https://github.com/UnBArqDsw/2020.1_G1_Triagil'

copyright: 'Copyright &copy; 2020 UnB Gama - FGA'

theme:
  name: material
  language: 'pt'
  logo: 'images/icon-white.png'
  favicon: 'images/icon-color-favicon.ico'
  palette:
    primary: 'light blue'
    accent: 'red'
  font:
    text: 'Roboto'

nav:
  - Início: index.md
  - Base:
    - Abordagens Específicas:
      - Pré-Rastriabilidade:
        - Rich Picture: base/abordagensEspecificas/pre/rp.md
      - Elicitação:
        - Brainstorming: base/abordagensEspecificas/elicitacao/brainstorming.md
        - Entrevista: base/abordagensEspecificas/elicitacao/entrevista.md
        - Questionário: base/abordagensEspecificas/elicitacao/questionario.md
        - Storyboard: base/abordagensEspecificas/elicitacao/storyboard.md
      - Modelagem:
        - Backlog do Produto: base/abordagensEspecificas/modelagem/backlog.md
      - Análise:
        - Verificação: base/abordagensEspecificas/analise/verificacao.md
        - Validação: base/abordagensEspecificas/analise/validacao.md
    - Apresentação:
      - Metodologias:
        - Scrum: base/apresentacao/metodologia/scrum.md
        - Programação Extrema(XP): base/apresentacao/metodologia/xp.md
    - Modelagem BPMN: base/modelagemBPMN/bpmn.md
    - Iniciativas Extras: base/extras/extras.md
